---
- hosts: gitlab
  gather_facts: False

  vars:
    - root_dir: "{{ playbook_dir }}"
#    - shared_dir: "{{ playbook_dir }}/../shared"

  vars_files:
    - ./gitlab_vars.yml

  pre_tasks:
    - debug: msg="Pre tasks section"
      tags: always

    - name: ANSIBLE PYTHON | install python 2
      raw: test -e /usr/bin/python || (apt -qqy update && apt install -qy python-minimal)
      become: yes
      tags: always

    - name:  UNPRIVILEGED USERS | Get acl dependency (ansible unprivileged user operations magic)
      apt: pkg="acl"
      become: yes
      tags: always

    - name: gather facts
      setup:
      tags: always

    - name: Include common pretasks
      include_tasks: "{{shared_dir}}/common_pretasks.yml"
      when: shared_dir is defined
      tags: always

    - name: Pre tasks round
      include_tasks: "tasks_custom_tools_pre.yml"

  roles:
     - {
         role: "sa-docker",
         tags: ["create"]         
       }
     - {
         role: "sa-python",
         tags: ["create"]         
       }
     - {
         role: "sa-python3",
         tags: ["create"]         
       }
     - {
         role: "sa-go",
         go_version: "1.11.5",
         tags: ["create"]         
       }
     - {
         role: "sa-go-gimme",
         go_version: "1.11.5",
         tags: ["create"]         
       }
     - {
         role: "sa-ruby",
         ruby_install_setsystem: false,
         ruby_version: 2.4.2,

         option_install_sampleapp: false,
         option_install_nginx_passenger: false,
         tags: ["create"]
       }       
     - {
         role: "sa-gitlab-runner",
         gitlab_groups: ["docker"]
       }
     - {
         role: "sa-node-nvm",
         nvm_version: "0.31.2",
         nodejs_version: "0.12",
         deploy_user: "gitlab-runner",
         option_nodejs_install_with_nvm: false,
         tags: ["create"]
       }


  tasks:

    - debug: msg="Tasks section"

    - name: Pre tasks round
      include_tasks: "tasks_custom_tools_post.yml"
